### PR TITLE
Auto-account.

### PR DESCRIPTION
**Pull request by EthanHarv**
Automates the process outlined in #12

Addresses #6, #7, #12, #13, #14, #15, and makes #16 unneeded. 

Works with any page, can use [this page](https://quizlet.com/explanations/questions/mark-each-statement-true-or-false-justify-each-answer-10-d86f1a8b-e06b-4c97-ac82-2175082c3a7a) as an example.

I feel fine uploading this, as it's literally just the exact same thing as logging out and making a new account.

Known Issue: Logs out users from their regular account.

### CODE REVIEW

**Comment by lebr0nli** [comment]
Thanks again!
I'm a little busy this week, I will review this pull request as quick as possible (maybe this Sunday or next week
Sorry 😥

**Comment by lebr0nli** [comment]
Since we don't need katex anymore,  I think we can remove it? Right?

**Comment by EthanHarv** [comment]
> Since we don't need katex anymore, I think we can remove it? Right?

Yep, I see no issue with that

**Comment by lebr0nli** [comment]
Not work for textbook solution?

**Comment by EthanHarv** [comment]
Hmm, I'll see if I can do anything about that

**Comment by EthanHarv** [comment]
Try now
Here's a [question page](https://quizlet.com/explanations/questions/mark-each-statement-true-or-false-justify-each-answer-a-the-symbol-if-means-for-every-b-the-negation-of-a-universal-statement-is-another-uni-27b85158-fbf56e7c-bfbb-4186-ba6d-8e47eb11021f) and here's a [textbook page](https://quizlet.com/explanations/textbook-solutions/discrete-mathematics-and-its-applications-7th-edition-9780073383095/chapter-8-exercises-45-c382d8b7-f0ba-4fb6-ae96-6eeb36477b92)

I've made it so it doesn't rely on specific `.mv7neh [whatever]` divs at any point, which should make it more robust.

**Comment by lebr0nli** [comment]
Oh, I know why my extension didn't work...
Because my Quizlet page is Chinese, pageContains will not work for me.
Can we just using `if(document.querySelector('.paywalled-section'))` to identify it?
But I'm not sure about it, since I didn't see the `This is your last free explanation`(in Chinese) banner.
Is `"This is your last free explanation"` banner's class is `paywalled-section` too?

**Comment by EthanHarv** [comment]
It appears that the section is always called `paywalled-section` even if the paywall isn't there.

However, quizlet creates a global variable Quizlet.LOGGED_IN, which I can pull from the header (can't access it directly).

Once mozilla signs my new version, it should hopefully work regardless of language.

**Comment by EthanHarv** [comment]
Hopefully should now work for any language

**Comment by lebr0nli** [comment]
> Hopefully should now work for any language

Yes, now it work!
I will merge this pull request later if there are no other bugs.

**Review by lebr0nli — COMMENTED** [review]
All good!

**Pull request merged**
